name: dcl-trainmarket
channels:
  - pytorch
  - conda-forge
  - gurobi
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - pytorch=2.5.1
  - gurobi
  - libprotobuf=4.25.3
  - protobuf=4.25.3
  - torchinfo
  - torchview
  - ruff
  - setuptools
  - wheel
  - readline
  - tk
  - xz
  - zlib
  - ncurses
  - sqlite
  - bzip2
  - ca-certificates
  - openssl
  - tzdata
  - libffi
  - joblib
  - scikit-learn
  - pip:
      - holidays==0.70
      - openpyxl==3.1.5
      - poetry==2.1.2
      - seaborn==0.13.2
      - torch-summary==1.4.5